In [98]:
import torch

In [119]:
from airquality import AirQuality

aq = AirQuality(data_dir='../data', is_subgraph=True, sub_size=70, sub_start='6.0-79.0-8002.0') #data

Found temporal data pickle, loading...	DONE!
Found a valid build, loading... 	DONE!


In [120]:
aq.dataframe()

nodes               32.0-5.0-7.0 6.0-1.0-11.0 6.0-1.0-12.0 6.0-1.0-13.0  \
channels                    PM25         PM25         PM25         PM25   
DateTime                                                                  
2018-01-01 05:00:00     9.000000    16.571428    19.714285    13.800000   
2018-01-01 06:00:00    10.857142    17.285715    17.714285    12.200000   
2018-01-01 07:00:00    10.000000    18.428572    16.571428    13.666667   
2018-01-01 08:00:00    28.000000    25.000000    13.000000     8.000000   
2018-01-01 09:00:00    26.000000    28.000000    21.000000    11.000000   
...                          ...          ...          ...          ...   
2021-01-01 05:00:00    30.000000    37.000000     7.000000     8.000000   
2021-01-01 06:00:00    27.000000    31.000000    56.000000    16.000000   
2021-01-01 07:00:00    26.000000    57.000000    37.000000    19.000000   
2021-01-01 08:00:00    11.021505    11.505377    10.473118    10.170251   
2021-01-01 09:00:00     9.247312    11.827957    10.000000    10.408602   

nodes               6.0-1.0-15.0 6.0-1.0-7.0 6.0-1.0-9.0 6.0-111.0-1004.0  \
channels                    PM25        PM25        PM25             PM25   
DateTime                                                                    
2018-01-01 05:00:00     6.000000   22.857143   16.285715        18.142857   
2018-01-01 06:00:00     4.000000   23.142857   12.714286        16.428572   
2018-01-01 07:00:00     5.000000   18.142857   12.428572        14.285714   
2018-01-01 08:00:00     4.000000   62.000000   63.000000        32.000000   
2018-01-01 09:00:00     8.000000   57.000000   26.000000        29.000000   
...                          ...         ...         ...              ...   
2021-01-01 05:00:00    16.000000   37.000000   27.000000        15.000000   
2021-01-01 06:00:00    16.000000   33.000000   22.000000        17.000000   
2021-01-01 07:00:00    28.000000   39.000000   87.000000         9.000000   
2021-01-01 08:00:00     7.161290   11.150537    9.795699         8.616488   
2021-01-01 09:00:00     8.118279    9.899642    8.806452         7.661290   

nodes               6.0-111.0-2002.0 6.0-111.0-3001.0  ... 6.0-85.0-2.0  \
channels                        PM25             PM25  ...         PM25   
DateTime                                               ...                
2018-01-01 05:00:00        16.000000        13.166667  ...     5.285714   
2018-01-01 06:00:00        15.571428        12.833333  ...     6.571429   
2018-01-01 07:00:00        11.428572        14.666667  ...     5.142857   
2018-01-01 08:00:00        61.000000        36.000000  ...    41.000000   
2018-01-01 09:00:00        56.000000        32.000000  ...    14.000000   
...                              ...              ...  ...          ...   
2021-01-01 05:00:00        24.000000         6.000000  ...    37.000000   
2021-01-01 06:00:00        22.000000         7.000000  ...    48.000000   
2021-01-01 07:00:00        16.000000         9.000000  ...    33.000000   
2021-01-01 08:00:00         6.789785         6.518587  ...     8.473118   
2021-01-01 09:00:00         7.046416         5.757604  ...     7.267281   

nodes               6.0-85.0-5.0 6.0-85.0-6.0 6.0-87.0-1005.0 6.0-87.0-7.0  \
channels                    PM25         PM25            PM25         PM25   
DateTime                                                                     
2018-01-01 05:00:00    16.142857    18.285715        7.571429     6.428571   
2018-01-01 06:00:00    14.571428    18.857143        7.857143     5.857143   
2018-01-01 07:00:00    11.857142    16.428572        8.285714     4.000000   
2018-01-01 08:00:00   101.000000    83.000000       20.000000    11.000000   
2018-01-01 09:00:00    81.000000    88.000000       18.000000     7.000000   
...                          ...          ...             ...          ...   
2021-01-01 05:00:00    37.000000    43.000000       26.000000     8.000000   
2021-01-01 06:00:00    47.000000    55.

In [84]:
len(aq.dataframe())

26309

In [83]:
aq.dataframe().iloc[0]

nodes            channels
1.0-103.0-11.0   PM25        10.900000
1.0-113.0-3.0    PM25        19.142857
1.0-73.0-23.0    PM25        11.440000
10.0-1.0-2.0     PM25         5.400000
10.0-3.0-1007.0  PM25        13.000000
                               ...    
9.0-3.0-1003.0   PM25         6.000000
9.0-3.0-25.0     PM25         8.000000
9.0-5.0-5.0      PM25         7.000000
9.0-9.0-2123.0   PM25         0.000000
9.0-9.0-27.0     PM25         3.000000
Name: 2018-01-01 05:00:00, Length: 695, dtype: float32

In [100]:
import pickle

In [122]:
#problemi:
# batch size diverse (quella la scartiamo)
# time window non sufficiente (forse non succede)


window = 12
batch_size = 32
n = len(aq.dataframe())
n_batches = n // (window * batch_size)
tens = None
i = 0
rows = 0
count_rows = 0
batches = []


#for index, row in aq.dataframe().iterrows():
while True:
    batch = None
    #i = rows + 1
    #count_rows = 1
    while batch is None or batch.shape[-1] < batch_size:
        tens = torch.FloatTensor(list(aq.dataframe().iloc[rows]))
        tens = tens.view(-1, len(tens))
        i = rows + 1
        count_rows = 1
        while count_rows <= window:
            tmp = aq.dataframe().iloc[i]
            tmp = torch.FloatTensor(list(tmp.copy()))
            tmp = tmp.view(-1, len(tmp))
            tens = torch.cat([tens, tmp], 0)
            i += 1
            count_rows += 1
            
        tens = tens.view(tens.shape[0], tens.shape[1], -1)

        if batch is None:
            batch = torch.clone(tens)
        else:
            batch = torch.cat([batch, tens], 2)
        rows += 1

    #rows += 1
    batches.append(torch.clone(batch))
    if len(batches) == n_batches:
        break

file_to_store = open("LSTM_batches.pickle", "wb")
pickle.dump(batches, file_to_store)
file_to_store.close()

In [123]:
file_to_read = open("LSTM_batches.pickle", "rb")
loaded_object = pickle.load(file_to_read)
file_to_read.close()

In [124]:
len(loaded_object)

68

In [126]:
loaded_object[0][1,:,0] == loaded_object[0][0,:,1]

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True])

In [89]:
len(batches)

3

In [91]:
batches[0][1,:,0] == batches[0][0,:,1]

tensor([True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, True, True, True, True, True, True, True,
        True, True, True, True, True, Tr

In [60]:
batches[1].shape

torch.Size([13, 695, 32])

In [64]:
batches[0][0, :, 1]

tensor([ 10.9000,  19.1429,  11.4400,   5.4000,  13.0000,  10.0000,   7.2000,
          5.2000,  10.0000,  12.0000,   8.0000,  11.0000,   7.8806,  18.1000,
          6.3363,   7.8000,   9.3621,  58.4000,   7.5500,   8.0516,  11.9200,
         33.3000,  59.7000,  24.1000,   8.0621,   8.4262,  49.2000,  73.5000,
          7.9444,   6.5000,   9.2645,  39.7000,   7.8455,  18.9000,  15.6000,
          9.9581,  18.6000,  11.7000,   7.3000,   6.5935,  16.9000,   7.1000,
         12.8000,  10.0000,   4.2857,   9.0000,  30.5000,   5.2857,   5.8571,
          0.4048,   5.0000,   0.8000,   4.2857,   5.1429,   3.5714,   5.3333,
         19.0000,  11.2667,   7.7143,  11.5143,  10.8429,  11.2000,   9.8429,
         10.3857,   8.9571,   8.5143,  14.2857,  10.4714,   9.2841,   6.3349,
         10.0429,   8.9000,  12.1143,   7.7429,   8.2571,  12.0000,   8.3429,
          8.3000,   6.7000,   7.5143,   5.1000,  14.3000,   7.2928,  12.8000,
         15.2000,  15.6000,   7.1000,  13.6000,  10.4571,   8.06

In [21]:
batches[0].shape

torch.Size([13, 695, 32])

In [26]:
batches[67].shape

torch.Size([13, 695, 32])

In [88]:
print('ciao')

ciao
